### PR TITLE
Add support of negative dimensions for Reshape

### PR DESCRIPTION
**Pull request by tungld**
This patch is to add support of negative dimensions for reshape.

FYI: It is found that all reshape operations in t[he MNIST model](https://s3.us.cloud-object-storage.appdomain.cloud/dlcompiler/model/mnist.onnx) use negative dimension.

### CODE REVIEW

**Comment by doru1004** [comment]
I'm not sure I understand what you mean by all reshape ops in MNIST have negative dimensions. This is what my MNIST model has:
```
%0 = "onnx.Reshape"(%arg0, %arg1) : (tensor<1x784xf32>, tensor<4xi32>) -> tensor<*xf32>
%19 = "onnx.Reshape"(%16, %arg8) : (tensor<*xf32>, tensor<2xi32>) -> tensor<*xf32>
```
The dimension array has known shape sizes which is expected. If that was unknown then it would not be able to produce a Ranked tensor as output since you don't know how many dimensions it has.

**Comment by tungld** [comment]
For this one
```
%0 = "onnx.Reshape"(%arg0, %arg1) : (tensor<1x784xf32>, tensor<4xi32>) -> tensor<*xf32>
```
I mean one of the **element values** of the tensor `tensor<4xi32>` is negative. We cannot see those values here but their types only. In [my MNIST model](https://s3.us.cloud-object-storage.appdomain.cloud/dlcompiler/model/mnist.onnx), `%arg1` has value of `[-1, 1, 28, 28]`, it mean the first element is negative and must be calculated from the other elements.

Elements of Reshape's 2nd argument can be: 
- `-1`: need to compute from the other elements
- `0`: get a value from the element of the same index in the input (Reshape's first argument). I fixed this in another PR which was merged.
- Not `-1`, `0`: just get it.

**Comment by doru1004** [comment]
@tungld sounds good. Thank you for the explanation.

What does it mean for a dimension to be computed "from the other elements"? What's the formula for computing that dimension?

**Comment by doru1004** [comment]
@tungld I think I know what you mean by "from the other dimensions". Do you mean that the remaining dimension is computed such that the output dimension has the same number of elements as the input?

**Comment by doru1004** [comment]
@also does the mean you can only have at most one negative entry?

**Comment by tungld** [comment]
Yes, we have at most one negative entry. To compute the actual value for the negative entry, we first get the tensor size by using the original shape (first argument of Reshape), then divide it by product of  the other entries. Since the other entries may have `0` value, we need compute the actual values for  `0` entries first and then the actual value for the negative entry.

> Do you mean that the remaining dimension is computed such that the output dimension has the same number of elements as the input?

It does only when the dimension has a value of 0.

Let me give some examples in form of `(original_shape, target_shape) -> result_shape`:
- ([2, 3, 4], [4, 2, 3]) -> [4, 2, 3]
- ([2, 3, 4], [2, -1, 2]) -> [2, 6, 2]
- ([2, 3, 4], [-1, 2, 3, 4]) -> [1, 2, 3, 4]
- ([2, 3, 4], [2, 0, 4, 1]) -> [2, 3, 4, 1]: `3` in the result shape is obtained from `3` in the original shape.
- ([2, 3, 4], [2, 0, 1, -1]) -> [2, 3, 1, 4]

**Pull request merged**
