### PR TITLE
Import scalar operands

### PR DESCRIPTION
**Pull request by tungld**
Scalar operands of an ONNX operation are not imported, so end-to-end tests related to scalar operands will fail. This patch is to fix such issue.

For example, variable `c = np.array(3.14).astype(np.float32)` in the test `scalar_bias_test` of gemm (https://github.com/onnx/onnx/blob/b3d201a25a09b738114ede8bb2fb128fe922ede5/onnx/backend/test/case/node/gemm.py#L63) is a scalar operand. In this case the test `scalar_bias_test` will fail.

### CODE REVIEW

**Comment by chentong319** [comment]
The final result of the scalar is imported as a tensor[1xelement_type]. When will the tensor be translated to a scalar? I guess there is no problem now because the type for operands in an OP is not really checked. We assume all the operands are tensor for shape inference too?

**Comment by tungld** [comment]
Yes, all operands should be tensor. Scalar operands here I mean are ONNX operands, not in MLIR. In the above example, c's shape is (), and we dont go into the for-loop, so I need to check the shape size to create a vector<1xtype> for that ONNX scalar oerand.

**Comment by tjingrant** [comment]
@tungld can you help me understand why currently scalar operands are not imported as 0-dimensional tensors?

**Comment by tungld** [comment]
I am not sure why. When I pushed a value of 0 to vector `dims` to try to make a 0-dimensional tensor, it did not work. It seems it's not a way to create a 0-dimensional vector in MLIR.

**Comment by tungld** [comment]
I printed out the output of frontend IR, and saw that the vector result was correctly produced as `vector<type>` for scalar operands. So this patch is not good. I am going to close this patch.

**Pull request closed without merging**
