### PR TITLE
Use a more compatible way to locate python interpreter executable.

### PR DESCRIPTION
**Pull request by tjingrant**
@tungld @imaihal
Does this patch look like a reasonable alternative to find python interpreter?

### CODE REVIEW

**Comment by doru1004** [comment]
Any particular reason for this change?

**Comment by tjingrant** [comment]
This is per https://github.com/clang-ykt/ONNF/issues/20.

**Comment by tungld** [comment]
@tjingrant it works well with my Anaconda environment. Thanks!

**Comment by imaihal** [comment]
@tjingrant This worked for both cmake 3.10.2 and 3.15.5. LGLM!

**Pull request merged**
