### PR TITLE
fix name of operator output in onnxop.inc and Operator.md

### PR DESCRIPTION
**Pull request by chentong319**
1. temporary solution for repeated name in operator's input and output.
   If happens, out_ is added as prefix of output name. Change is applied to both onnxop.inc and Operator.md

2. Put the corresponding Operator.md into ONNF/doc

3. some minor cleanup

### CODE REVIEW

**Comment by tjingrant** [comment]
I'm looking at the CI issue (seems to be triggered by DocCheck).

**Comment by tjingrant** [comment]
OK, seems like buildbot is happy now.

**Comment by chentong319** [comment]
thanks @tjingrant . Could you explain why directive.py is affected?

**Comment by tjingrant** [comment]
@chentong319 I forgot to handle trailing empty lines in DocCheck.

**Comment by doru1004** [comment]
@tjingrant @chentong319 why did we have to include the Operator.md separately ? I thought we were picking it up directly from our ONNX submodule!

**Comment by tjingrant** [comment]
I also wonder what's the benefit of including Operator.md?

**Comment by chentong319** [comment]
@tjingrant The ONNX specification uses same name for input and output for some operator, which is not allowed by MLIR. When this situation happens, I add prefix out_ to output. Such change resulted a slightly different Operators.md, which I put here. @doru1004 asked to remove it and I will put a fix.

**Comment by tjingrant** [comment]
@chentong319 a compromise solution can be achieved by generating a operation documentation straight from TableGen. I can work on this tmrw if you @doru1004 @chentong319 both agree this is a good idea.

**Comment by chentong319** [comment]
@tjingrant I was thinking this too, more for the Operations we added. Should the tool be part of MLIR, or ONNF?

**Comment by AlexandreEichenberger** [comment]
adding doc "for free" in the onnx.td would be definitely in the philosophy of MLIR. So I would strongly support this, if it's not too hard

**Comment by chentong319** [comment]
First check whether MLIR already has such tool

**Comment by doru1004** [comment]
@tjingrant I would also be very much in favor of something like that. It's actually what we need and we can also include the new ops we added.

**Comment by tjingrant** [comment]
Yes there is such a tool in MLIR today and I intend to use it. It's indeed documentation "for free".

**Comment by tjingrant** [comment]
@chentong319 could you re-open the PR? I will add more commits to it tmrw.

**Comment by chentong319** [comment]
@tjingrant @doru1004 I reopened PR with Operators.md removed.

**Pull request merged**
