### PR TITLE
Chentong319 attribute with variant

### PR DESCRIPTION
**Pull request by tjingrant**
Editing https://github.com/clang-ykt/ONNF/pull/10 to remove the dependency on boost.

### CODE REVIEW

**Comment by tjingrant** [comment]
Reposting @chentong319 's original PR here:

design change:
First import all the attributes specified for a node purely based on the info carried by onnx node
second import the default attributes that have no been specified for this node. The default attribute list is generated by gen_doc.py
implementation change:
variant is used to represent different type of value. converter from string is avoided.
future work
some types for attribute in onnx document are not supported yet
should build a table of function for each operation. The table initialization will be generated from the script. I feel the code is neater in such a way. Also, more efficient if we add some common code for each onnx operation.
our script to generate code should be separated from gen_doc.py

**Comment by tjingrant** [comment]
@chentong319 @doru1004, I'm done removing boost from this patch. Please help review.
Some extra modifications include:
- I don't see a need to use a lambda visitor, which seems to involve a lot of template meta-programming. I just implemented the struct-visitor equivalent and the code seems cleaner.
- ONNX attribute type int means int64, not int32.
- Import list-like attributes using ArrayAttr instead of dense element attribute (which should only be used if attribute content is a tensor).
- Fix clang-tidy warnings (most about avoiding making copies of various data-structures).

**Comment by tjingrant** [comment]
@chentong319 could you please add some FileCheck tests (from ONNX protobufs to ONNX Dialect) to ensure attribute importing is correct?

**Comment by tungld** [comment]
Previously, when importing an ONNX operator, say LeakyRelu, its attribute `alpha` has a name `Leaky.alpha`, where `Leaky` is its op type. May I confirm that, with this patch, the attribute `alpha` will have a name of `alpha`? If so, we should update lowering of operators that have attributes also.

**Comment by tungld** [comment]
Does this patch support an attribute whose type is List? For reduction ops like ReductionMax, ReductionMin, their attribute `axes` is a list of ints.

**Comment by chentong319** [comment]
@tungld 
1. Yes, the attribute name is not prefixed with OP name. I think it is kind of redundant. 
2. The new patch can handle a list of int or float.

**Comment by tungld** [comment]
Thanks, @chentong319!

**Comment by tjingrant** [comment]
@doru1004 could you help take a look at some of the merge conflicts? Seem to stem from the Conv/MaxPool ops patch recently merged. You probably have a better idea of what's going on.

**Comment by doru1004** [comment]
> @doru1004 could you help take a look at some of the merge conflicts? Seem to stem from the Conv/MaxPool ops patch recently merged. You probably have a better idea of what's going on.

For sure, I see what's happening. I'll resolve the conflict in a bit.

**Comment by tungld** [comment]
Backend tests failed because attribute's name has changed from "op_type.attribute_name" to "attribute.name" in this patch.

**Comment by tjingrant** [comment]
OK, tests are restored. Thanks @tungld , I learnt about this issue from you yesterday!

**Pull request merged**
