### PR TITLE
Infer shape for MatMul operation

### PR DESCRIPTION
**Pull request by doru1004**
This patch adds support for inferring the shape of the result of a matrix multiply operation according to the semantics of numpy.matmul.

### CODE REVIEW

**Comment by tungld** [comment]
Should we check scalar operands? According to numpy.matmul semantics, multiplication by scalars is not allowed.

**Comment by doru1004** [comment]
> Should we check scalar operands? According to numpy.matmul semantics, multiplication by scalars is not allowed.

I already check if operands are ranked tensors.

**Comment by tjingrant** [comment]
> I already check if operands are ranked tensors.

Scalars can be 0-d tensors? Which means they are ranked. I'm not sure if this is potentially an issue.

**Comment by doru1004** [comment]
> > I already check if operands are ranked tensors.
> 
> Scalars can be 0-d tensors? Which means they are ranked. I'm not sure if this is potentially an issue.

Got it. I'll make sure rank is greater or equal to 1.

**Pull request merged**
