### PR TITLE
Allow importing variadic inputs/outputs of onnx operators

### PR DESCRIPTION
**Pull request by tungld**
Currently, ops with variadic inputs/outputs are imported as ops with **one** input and **one** output. Hence, their e2e tests would not work.

This patch is to support importing ops with homogeneous variadic inputs/outputs.

### CODE REVIEW

**Comment by tungld** [comment]
@tjingrant This helps fix end-to-end tests for variadic operations.

**Comment by tjingrant** [comment]
Hi @tungld , op_build_table.inc is automatically generated. We may need to modify `gen_doc.py` instead of editing the generated file directly.

In the future, generated files will be clearly marked. Sorry for any confusion in the mean time.

**Comment by tjingrant** [comment]
Also we might want to merge #25 first to avoid potential conflict.

**Comment by tungld** [comment]
So I will go back with this then.

**Comment by tungld** [comment]
@tjingrant Could you please teach me how to generate `op_build_table.inc` using `gen_doc.py`? Thanks!

**Comment by tungld** [comment]
I was able to generate `op_build_table.inc` by using `gen_doc.py`.

**Pull request merged**
