### PR TITLE
Update to latest MLIR

### PR DESCRIPTION
**Pull request by tjingrant**
1. mlir::Value used to be passed around by pointer, but MLIR recently moved to pass around mlir::Value by value. Thus I made onnf to pass by value as well.
2. Change env variables used to determine the location of LLVM and MLIR to `LLVM_PROJ_SRC` and `LLVM_PROJ_BUILD`. This change is necessitated by MLIR moving into the llvm-project monorepo.
    - `LLVM_PROJ_SRC` points to the root of llvm-project monorepo.
    - `LLVM_PROJ_BUILD` points to the root of object files built from llvm-project.

### CODE REVIEW

**Comment by tungld** [comment]
It seems we should update the Installation session of `README.md` as well.

**Comment by tjingrant** [comment]
@tungld yes, I'm working on it. Sorry for the confusion.

**Comment by tjingrant** [comment]
Since we are on it, here's the script I used in the buildbot: https://github.com/clang-ykt/ONNF/blob/master/.circleci/install-mlir.sh to install latest mlir.

**Comment by tungld** [comment]
Thanks, @tjingrant. FYI, I fixed a bug in MLIR which caused wrong results when using StridedMemRefType: https://github.com/tensorflow/mlir/pull/338. It was merged into MLIR. Please make sure that our MLIR version covers such fixing.

**Comment by tjingrant** [comment]
@tungld the current buildbot always pulls MLIR from the tip of the branch (of llvm-project monorepo). If your patch is merged into llvm-project, we should have it covered.

Another issue that I've found out is that because the order of function argument evaluation is unspecified in C++ standard, nested IR emission logics like this one I fixed (https://github.com/clang-ykt/ONNF/pull/7/commits/eadf33d8164bb836844faac496b17b8812689e50) can cause trouble because the MLIR operations emitted can be arbitrarily ordered, causing FileCheck test to fail. In the example referenced, there's no guarantee which operation (Sub or Add) will appear first.

**Comment by tungld** [comment]
I see. Thanks for the information!

**Pull request merged**
