### PR TITLE
[NFC] Categorize ONNX ops lowering

### PR DESCRIPTION
**Pull request by tungld**
This patch is implementation of the proposal #24, to organize the lower-frontend pass into categories following the ONNX taxonomy (c.f. https://github.com/onnx/onnx/tree/master/onnx/defs). This patch was part of the closed PR #30.

Modifications include:
1.  Move the lowering code from `pass` directory to `conversion` directory, mirroring MLIR project setup here: https://github.com/llvm/llvm-project/tree/master/mlir/lib/Conversion.
- `onnx_to_krnl` directory in `conversion` directory: convert ONNX frontend dialect to Krnl dialect. 
2. Organize `onnx_to_krnl`'s rewrite patterns into categories following the ONNX taxonomy.
- The main source code for `onnx_to_krnl` is `conversion/onnx_to_krnl/convert_onnx_to_krnl.cpp`.
- Each category corresponds to a folder. Each file in a folder is for lowering operators that have the same computation pattern. For example, some ops in categories `math` and `tensor` are as follows:
    - `conversion/onnx_to_krnl/rewrite_patterns/math/elementwise.inc`: patterns for lowering element-wise math ops, and
    - `conversion/onnx_to_krnl/rewrite_patterns/tensor/reshape.inc`: patterns for lowering the reshape op, a tensor-related operator.

### CODE REVIEW

**Comment by tjingrant** [comment]
@tungld can you take a look at the buildbot error?
Also, this seems like a perfect opportunity to move the lowering code from `pass` directory to `conversion` directory, mirroring MLIR project setup here:

https://github.com/llvm/llvm-project/tree/master/mlir/lib/Conversion

**Comment by tungld** [comment]
@tjingrant I forgot to push one file, i.e. reduction.inc.

**Comment by tungld** [comment]
Hi @tjingrant and @doru1004, I am thinking should we move the lowering codes from `transform` directory to `conversion` directory also? As I understand `transform` directory might be more suitable for optimizations like program transformations such as fusion, data movement, etc.

**Comment by tjingrant** [comment]
Hi @tungld yes, I think Alex and Doru would also agree that's a good idea as we briefly discussed this point before. However, let's focus only on ONNX -> Krnl lowering code in this patch (so as to keep changes local and avoid conflicts that may delay this patch).

**Comment by tungld** [comment]
Thanks @tjingrant for the explanation. I just changed file/directory names following our current naming convention.

**Comment by doru1004** [comment]
Is this patch just a reorganization of the source tree structure or are there any functional changes?
If there are no function changes in this patch please mark it as NFC.

**Comment by tungld** [comment]
There are no function changes. I have no permission to label this patch, so I just added NFC to the title.

**Comment by tjingrant** [comment]
@doru1004 it'd be better not to merge any more patches until this one gets merged. Otherwise, there'll be more burden to resolve conflicts. If you approve of this patch, I'll merge tomorrow as soon as the patch is updated to resolve conflict.

**Comment by tungld** [comment]
@doru1004 I confirm that when I change the content of an include file in the lower-frontend pass, rebuilding can detect it and rebuild the lower-frontend pass.

**Pull request merged**
